name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run tests
        run: uv run pytest --junit-xml=test-results.xml

      - name: 'Upload junit-xml artifacts'
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results--${{github.run_id}}--${{github.run_attempt}}.xml
          path: test-results.xml
          retention-days: 30
